node_installed_windows: '& c:/users/liamwinters/appdata/local/programs/python/python312/python.exe
  "c:/users/liamwinters/onedrive - wico vzw/bureaublad/vulcanopanel/run.py"'
program_run_before_windows: y
